#!/usr/bin/env bash
# Configure my domain zone so that the subdomain www points to my load-balancer IP (lb-01)

check_subdomain()
{
    local sub=$1
    local domain=$2
    
    # Use +short to get only the IP address
    local destination
    destination=$(dig +short "$sub.$domain" | tail -n1)

    # Output 'A' as record type when an IP is returned
    if [ -n "$destination" ]; then
        echo "The subdomain $sub is a A record and points to $destination"
    else
        echo "The subdomain $sub is a  record and points to "
    fi
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        check_subdomain "$sub" "$domain"
    done
else
    check_subdomain "$subdomain" "$domain"
fi
