#!/usr/bin/env bash
# Displays DNS subdomain information using dig and awk

domain="$1"
subdomain="$2"

# Function to query dig and format output using awk
audit_subdomain() {
    local sub="$1"
    local dom="$2"
    dig "${sub}.${dom}" | awk -v s="$sub" '/ANSWER SECTION:/ {
        getline
        print "The subdomain " s " is a " $4 " record and points to " $5
    }'
}

# Ignore shellcheck case SC2086
# shellcheck disable=SC2086
if [ -n "$subdomain" ]; then
    audit_subdomain "$subdomain" "$domain"
else
    for sub in www lb-01 web-01 web-02; do
        audit_subdomain "$sub" "$domain"
    done
fi
