#!/usr/bin/env bash
# Script that displays information about subdomains for a given domain

domain="$1"
subdomain="$2"

check_subdomain() {
    local sub="$1"
    local dom="$2"

    res=$(dig "${sub}.${dom}" | awk '/^;; ANSWER SECTION:/ {flag=1; next} /^$/ {flag=0} flag {print $4, $5; exit}')
    record_type=$(echo "$res" | awk '{print $1}')
    destination=$(echo "$res" | awk '{print $2}')

    echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
}

if [ -n "$subdomain" ]; then
    check_subdomain "$subdomain" "$domain"
else
    check_subdomain "www" "$domain"
    check_subdomain "lb-01" "$domain"
    check_subdomain "web-01" "$domain"
    check_subdomain "web-02" "$domain"
fi
